version: '3.8'

services:
  jetbrainsai2api:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      # 从 .env 文件读取的环境变量会自动传递
      - PORT=${PORT:-8000}
      - CLIENT_API_KEYS=${CLIENT_API_KEYS}
      - JETBRAINS_JWTS=${JETBRAINS_JWTS}
      - AVAILABLE_MODELS=${AVAILABLE_MODELS}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/v1/models", "-H", "Authorization: Bearer ${CLIENT_API_KEYS%%,*}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
